name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg SDKVERSION=${{ secrets.VERSION }} --tag ${{ secrets.IMAGE_NAME }}:${{ secrets.VERSION }} --tag ${{ secrets.IMAGE_NAME }}:latest
